
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongo

volumes:
  mongo-data:

